version: '3'

services:
  mongo:
    image: 'mongo:4.0.5'
    restart: always          

  katana:
    build: .
    image: katana
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "katana.app:create_app()"
    volumes:
      - '.:/katana'
    ports:
      - '8000:8000'
    restart: always
